import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/shared/Navbar/Navbar";
import { NavbarProvider } from "./providers/NavbarProvider";
import { Sidebar } from "./components/shared/Navbar/Sidebar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavbarProvider>
        <body className="bg-0 overflow-hidden flex flex-col relative h-[100vh]">
          <Navbar />
          <Sidebar />
          <div className="flex flex-1 flex-col">{children}</div>
        </body>
      </NavbarProvider>
    </html>
  );
}
