import type { Metadata } from "next";
import "./globals.css";
import { User } from "@deemlol/next-icons";
import { FeedbackDialog } from "./components/FeedbackDialog";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#e9e4d4]">
        {children}
        {/* <div className="fixed right-10 bottom-10 w-16 h-16 bg-red-500 rounded-full"></div> */}
        <FeedbackDialog>
        <div className="fixed bottom-10 right-10 bg-red-500 p-5 rounded-full hover:cursor-pointer">
            <User size={24} color="#FFFFFF" />
        </div>
        </FeedbackDialog>
      </body>
    </html>
  );
}
