import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import { NavbarProvider } from "../providers/NavbarProvider";
import { Sidebar } from "../components/Navbar/Sidebar";
import MessengerBubble from "../components/MessengerBubble/MessengerBubble";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavbarProvider>
        <body className="bg-0 flex flex-col relative h-screen">
          <Navbar />
          <Sidebar />
          <MessengerBubble/>
          <div className="flex flex-1 flex-col">{children}</div>
        </body>
      </NavbarProvider>
    </html>
  );
}
